FROM tomcat:8.0.20-jre8
MAINTAINER Ashok <ashok@oracle.com>
EXPOSE 8080
COPY /var/lib/jenkins/workspace/Sample_pipeline/maven-web-app-master/maven-web-app-master/target/maven-web-app.war /usr/local/tomcat/webapps/maven-web-app.war
